### ISSUE TITLE
Document of controlling the device

### ISSUE THREAD

**Issue by Amaarillo** [jerwuqu/dreamcolor#1]
@jerwuqu
Is there any documentation on how to remote/control the device? How did you know the hex command for controlling the device, for example turn on with [0x7e, 0x04, 0x04, 0x01, 0xff, 0xff, 0xff, 0x00, 0xef]? I want to know this because I want to have more functionality, but also because the dim function is changing the color to white when changing the light intensity, which I dont want (I only want to change the light intensity with the last color selected).

**Comment by jerwuqu** [comment]
Hello! 
I got the commands by using a debug proxy and figured out the RGB stuff by simply looking at different commands, so I don't actually know all of them.
If the feature you're looking for is supported in the app, then you could do the same. I don't remember the name right now, but any program that allows proxying and viewing UDP packets should work.

Tell me if you need any help with that :)

**Comment by Amaarillo** [comment]
@jerwuqu
Thanks for the answer!

I have tried some programs like Fiddler or Charles debugging proxy, where I am able to see HTTP and HTTPS traffic on my Iphone (which I can see on my PC), but not UDP. I have tried the port forwarding thing with Charles debugging proxy to be able to view UDP packets (link below), but didn't manage. I don't know how to listen to UDP packets with these programs, how can I do that?

https://www.charlesproxy.com/documentation/proxying/port-forwarding/

**Comment by jerwuqu** [comment]
Yeah, Fiddler and Charles are both excellent proxies for debugging.
Something like Wireshark would work on PC.
I think I was using this on Android which should work fine: https://play.google.com/store/apps/details?id=app.greyshirts.sslcapture

Feel free to create pull requests and stuff if you discover anything cool :)

**Comment by Amaarillo** [comment]
I am using Charles and I managed to view HTTP/HTTPS traffic, but not with UDP. I think I have to setup a SOCKS proxy in order to view UDP on Charles. I have enabled SOCKS proxy with port 8889 in proxy settings on Charles and tried to go in wifi settings on my Iphone to put my IP-adress of the computer with port 8889, but does not work. I have done some researches, and they say that I have to setup a SOCKS proxy on the iPhone in a special way or something, but cannot find anything on how to do so. Herew is the link of that: https://stackoverflow.com/questions/20132970/udp-packets-from-iphone-could-not-be-captured-in-charles-web-proxy-tool

As said, I have managed to view HTTP/HTTPS traffic, where I use the port 8888 (HTTP proxy mode). So when I type this port and IP-adress of my computer in wifi settings on my Iphone, I can view HTTP/HTTPS traffic. But SOCKS proxy was not as easy as that by just changing the port in wifi settings on the Iphone for my network to 8889. I have to do something more, which I do not know how. I have also done some researches, but have not understood so much since I am not an expert on this topic. I would appreciate if you could help me with this so I can listen to UDP packets. What is missing to be able to view UDP packets?

Thanks for trying to help by the way!

**Comment by Amaarillo** [comment]
Hello!

I have solved it by using an app on my iPhone called Pirni pro, which creates a log of the network traffic between my phone and other devices. Then I sent this log to my computer to open it by wireshark, where I could see the all UDP packets. I tried much by using a debug proxy like you said, but did not manage at all, but thanks to Pirni pro app, I could view the UDP packets.

Thanks for your help!

**Comment by Amaarillo** [comment]
I just wonder an other thing. I can see that we can choose to broadcast or not with your code. Whats the difference between if I do so or not? For now, it works when I do not broadcast, but why should I broadcast since I can do that too?

**Comment by jerwuqu** [comment]
Hello again! Sorry for the delay.

Great that you solved it! :) 

Broadcasting is good if you have multiple lights and want to control all of them with just one command ^^
